branches:
  only:
    - jdk-next-win

version: '{build}'

image: Visual Studio 2017

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk12
platform:
  - x64

install:
  - appveyor DownloadFile https://download.java.net/java/early_access/jdk12/22/GPL/openjdk-12-ea+22_windows-x64_bin.zip -FileName C:\jdk.zip
  - ps: Expand-Archive -Path C:\jdk.zip -DestinationPath C:\jdk12 -Verbose
  - cmd: SET JAVA_HOME=C:\jdk12\jdk-12
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - cmd: refreshenv
  - java -version
  - mvn -version

build_script:
  - mvn --batch-mode clean package -DskipTests

test_script:
  - mvn --batch-mode clean package

cache:
 - C:\Users\appveyor\.m2
